name: Integration

on: pull_request
    
jobs:
  validate:
    name: Validate pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:ci
      - name: Build
        run: npm run build

  auto_review_and_merge:
    if: github.head_ref == 'main' && github.base_ref == 'develop'
    runs-on: ubuntu-latest
    name: Auto review and merge
    steps:
      - name: Enable auto merge
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          pull-request-number: ${{ github.event.number }}
      - name: Auto approve pull request
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.number }}  
